# Implementacion de API

In [ ]:
# Importando los datos de prueba
import pandas as pd

# Datos de prueba para probar el modelo
X_test = pd.read_csv("X_test (1).csv")
y_test = pd.read_csv("y_test (1).csv")

if len(X_test) != len(y_test):
    raise ValueError("X_test y y_test no tienen el mismo numero de filas.")

# Combinar los DataFrames
data_test = pd.concat([X_test, y_test], axis=1)

# Mostrar el DataFrame combinado
display(data_test)

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,CompanyName,SalesPerson,EmailAddress,Phone,PasswordHash,PasswordSalt,rowguid,DaysSinceModified
0,29900,0,298,0,255,5,314,4,422,38,156,324,594,518
1,30083,0,105,11,370,0,6,4,140,386,252,231,603,427
2,47,1,112,11,196,5,176,4,148,65,189,78,47,62
3,29757,0,99,26,163,5,23,5,132,339,152,399,819,31
4,156,0,183,11,53,4,221,1,247,370,0,416,682,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,677,1,42,13,309,5,385,4,55,192,133,22,66,396
164,29889,1,133,26,249,5,334,8,180,112,112,212,668,0
165,348,0,224,13,12,5,40,5,311,375,172,100,620,31
166,29913,0,17,26,264,5,124,5,24,266,154,17,652,396
167,30050,0,178,26,352,5,227,2,242,24,378,396,108,427

In [12]:
features = data_test.drop(columns=["DaysSinceModified"])  # Excluir la columna objetivo
#ids = data_test["CustomerID"]  # Guardar los IDs para despliegue

# Convertir caracteristicas a un diccionario para la API
data_dict = features.to_dict(orient='list')

In [13]:
features

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,CompanyName,SalesPerson,EmailAddress,Phone,PasswordHash,PasswordSalt,rowguid
0,29900,0,298,0,255,5,314,4,422,38,156,324,594
1,30083,0,105,11,370,0,6,4,140,386,252,231,603
2,47,1,112,11,196,5,176,4,148,65,189,78,47
3,29757,0,99,26,163,5,23,5,132,339,152,399,819
4,156,0,183,11,53,4,221,1,247,370,0,416,682
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,677,1,42,13,309,5,385,4,55,192,133,22,66
164,29889,1,133,26,249,5,334,8,180,112,112,212,668
165,348,0,224,13,12,5,40,5,311,375,172,100,620
166,29913,0,17,26,264,5,124,5,24,266,154,17,652
167,30050,0,178,26,352,5,227,2,242,24,378,396,108

In [14]:
# Formatear los datos para la API
import json
data_json = json.dumps({"data": [data_dict]})

# Leer la URI 
with open("uri.json", "r") as suri:
    scoring_uri = json.load(suri)["URI"][0]

In [15]:
# Enviar los datos a la API
import requests
headers = {"Content-Type": "application/json"}
response = requests.post(scoring_uri, data=data_json, headers=headers)

In [16]:
response.status_code  # Verificar el estado de la respuesta

200

In [19]:
# Procesar la respuesta de la API
if response.status_code == 200:
    result = json.loads(response.json())  
    data_test["DaysSinceModified"] = result 
    print(result) 
    output = data_test[["CustomerID", "FirstName", "LastName", "DaysSinceModified"]]  
    display(output)  
else:
    print(f"Error: {response.text}")

[351.45, 412.95, 303.23, 411.05, 224.05, 336.86, 338.23, 246.42, 96.77, 576.55, 506.4, 278.58, 343.98, 791.6, 376.32, 340.42, 327.56, 449.19, 745.19, 227.55, 433.36, 215.06, 334.15, 598.39, 243.27, 391.2, 622.33, 448.82, 501.25, 388.15, 327.18, 403.38, 297.76, 613.57, 656.1, 185.61, 255.92, 590.91, 376.86, 174.93, 332.3, 404.92, 481.08, 367.87, 559.35, 375.97, 445.85, 377.01, 262.65, 452.91, 503.1, 319.77, 358.55, 200.26, 581.74, 320.34, 358.67, 237.01, 123.84, 136.49, 408.83, 665.71, 467.98, 247.03, 396.69, 336.11, 390.15, 671.77, 365.34, 444.33, 643.1, 241.81, 304.84, 201.33, 535.53, 670.44, 348.55, 248.37, 512.61, 645.29, 602.88, 339.33, 437.95, 256.94, 476.4, 375.41, 494.62, 551.43, 221.73, 339.83, 393.05, 320.71, 551.68, 717.39, 567.97, 475.37, 395.49, 347.74, 248.68, 993.87, 394.97, 754.51, 580.97, 566.89, 194.09, 477.44, 366.89, 640.76, 557.04, 181.94, 309.46, 443.53, 674.28, 595.11, 450.18, 578.54, 284.74, 197.61, 250.46, 159.21, 367.3, 307.83, 240.6, 634.8, 274.46, 588.01, 297.43, 348.3, 274.55, 467.21, 198.92, 79.38, 643.08, 340.3, 326.82, 645.2, 363.37, 396.45, 491.01, 454.59, 615.46, 169.78, 376.35, 150.28, 185.45, 326.2, 675.51, 431.74, 271.7, 105.83, 677.76, 194.38, 309.27, 535.85, 363.9, 349.86, 367.95, 572.2, 1385.5, 339.68, 259.04, 521.15, 178.75, 430.12, 232.48, 166.44, 431.31, 607.51]

     CustomerID  FirstName  LastName  DaysSinceModified
0         29900        298       255             351.45
1         30083        105       370             412.95
2            47        112       196             303.23
3         29757         99       163             411.05
4           156        183        53             224.05
..          ...        ...       ...                ...
163         677         42       309             430.12
164       29889        133       249             232.48
165         348        224        12             166.44
166       29913         17       264             431.31
167       30050        178       352             607.51

[168 rows x 4 columns]